initial push, WIP
erisyon/plaster pull request #102
Opened 2020-09-22 18:51 UTC by rossdavidh

Not actually done yet,  just PR'ing so you can see WIP more easily.

2020-09-22 19:04 UTC, zack-erisyon requested changes

2020-09-22 19:04 UTC, zack-erisyon commented on plaster/run/call_bag.py
> +        pred = self.pred_peps__pros()["pro_i"].values
Better form is to use .pro_i like...
self.true_peps__pros().pro_i.values

2020-09-22 19:04 UTC, zack-erisyon commented on plaster/run/call_bag.py
>          # At this point true, pred, scores are sorted WHOLE SET OF ALL PEPTIDES
Just change word "peptide" to protein

2020-09-22 19:04 UTC, zack-erisyon commented on plaster/run/call_bag.py
>                  np.concatenate((self.df.true_pep_iz[1:], self.df.pred_pep_iz))
It should be pro_iz_subset now

2020-09-22 19:04 UTC, zack-erisyon commented on plaster/run/call_bag.py
>          # At this point, true_ and pred_in_subset_mask are masks on the original set.
Doc string please. What is "pop"?

2020-09-22 19:04 UTC, zack-erisyon commented on plaster/run/call_bag.py
>              ]
be careful -- this is refering to train_pep_recalls in this pro funtion

2020-09-22 19:06 UTC, rossdavidh commented on plaster/run/call_bag.py
>          # At this point, true_ and pred_in_subset_mask are masks on the original set.
"peptide or protein", but I'll add a docstring

2020-09-22 19:07 UTC, rossdavidh commented on plaster/run/call_bag.py
>              ]
Thanks!

2020-09-22 19:17 UTC, rossdavidh commented on plaster/run/call_bag.py
> +        return self.pr_curve_either('pep', \
Hmmm...I somehow had the impression that "black" was run automatically when I did a git commit.

2020-09-22 19:43 UTC, ossareh commented on plaster/run/call_bag.py
> +        return self.pr_curve_either('pep', \
AFAICT it's only setup in erisyon/internal.

The internal repository has [`.pre-commit-config.yaml`](https://github.com/erisyon/internal/blob/master/.pre-commit-config.yaml), which is required for the `git commit` portion of this. However, in the container, it has recently been disabled by @zack ( https://github.com/erisyon/internal/blame/master/scripts/p_internal.py#L731-L733 ).

If you want to enable it for erisyon/plaster you'll need to create a config file, and then issue `pre-commit install`.

2020-09-22 19:45 UTC, rossdavidh commented on plaster/run/call_bag.py
> +        return self.pr_curve_either('pep', \
I see, thanks!

2020-09-24 18:48 UTC, ossareh reviewed
I'm just a spectator here asking questions, so please don't index too highly on my thoughts :)

I see that this hasn't been blackened. Is it time to switch pre-commit on for the plaster repo?

2020-09-24 18:48 UTC, ossareh commented on plaster/run/call_bag.py
> +        self.df["Order"] = np.arange(len(self.df))
Is `"Order"` coming from something external? I"m surprised to see a capital "O" here.

2020-09-24 19:59 UTC, rossdavidh commented on plaster/run/call_bag.py
> +        self.df["Order"] = np.arange(len(self.df))
Really, I would prefer to drop that column after I'm done using it.  I'll do that before the end of the day.

2020-09-25 19:41 UTC, rossdavidh commented
Changed to address Mike's concern on the capitalized key, and Zack's various comments from before today.  Let me know if there's something else I need to do to mark it as "ready", as far as I know.

2020-09-25 20:01 UTC, danwinkler approved these changes
Looks good, make sure to run it through black. I didn't go too deep into making sure the logic is correct.

2020-09-25 20:33 UTC, rossdavidh commented on plaster/run/call_bag.py
> +        return self.pr_curve_either('pep', \
Done.

2020-09-25 20:33 UTC, rossdavidh commented on plaster/run/call_bag.py
>          # At this point true, pred, scores are sorted WHOLE SET OF ALL PEPTIDES
Done.

2020-09-25 20:38 UTC, rossdavidh commented
Did all changes requested by Zack,  Mike, and Dan, will defer Dan's idea of an Enum to when we add a third type of PR curve, so that more time can be spent on how exactly that should be designed.  I think it's a good idea, but opens a bit of a bigger topic on how to generalize across PR types, which probably will happen better when we actually are ready to introduce a third one.  Since the protein PR curve is needed ASAP, and I want to consider the more generalized PR curve more carefully, I'm just going with the current method for the moment.  I'll add a task to the backlog to look into this more thoroughly in the future.

2020-09-25 20:39 UTC, merged