Fix sim_v2 table issue and auto normalize abundance data
erisyon/plaster pull request #114
Opened 2020-09-30 20:22 UTC by danwinkler

2020-09-30 20:52 UTC, zack-erisyon requested changes
Did you get a run and see if any of this normalization even matters?

2020-09-30 20:52 UTC, zack-erisyon commented on plaster/run/prep/zests/zest_prep_params.py
> +    with zest.mock(log.info) as m_log:
These should each be an "it_" type sub test

2020-10-01 17:30 UTC, danwinkler commented
Without normalization the results are pretty drastically different from the normalized data. I can't validate either one so I'm just going to assume the normalized is correct (because that's what we've been doing/using thus far).

2020-10-01 18:37 UTC, zack-erisyon approved these changes

2020-10-01 19:53 UTC, merged