Fix some bugs
erisyon/plaster pull request #167
Opened 2020-12-23 19:01 UTC by danwinkler

- fix classify_v2 generator bug
- add malloc checks, convert alloca->malloc in sigprocv2
- hack to fix zplots.im stack

2020-12-23 23:49 UTC, zack-erisyon requested changes
Ah! No! I need my K&R braces back. Can you get the editor to un-fuck this?

2020-12-28 16:24 UTC, danwinkler commented on plaster/run/sigproc_v2/c_radiometry/radiometry.c
> +    Float64 *psf_pixels = (Float64 *)malloc(sizeof(Float64) * mea_sq);
code change

2020-12-28 16:24 UTC, danwinkler commented on plaster/run/sigproc_v2/c_radiometry/radiometry.c
> +    free(psf_pixels);
code change

2020-12-28 16:42 UTC, danwinkler commented on plaster/run/sigproc_v2/c_sub_pixel_align/sub_pixel_align.c
> +    ensure(offset_samples != NULL, "malloc failed");
code change

2020-12-28 16:42 UTC, danwinkler commented on plaster/run/sigproc_v2/c_sub_pixel_align/sub_pixel_align.c
> +    ensure(slice_buffer != NULL, "malloc failed");
code change

2020-12-28 16:43 UTC, danwinkler commented on plaster/tools/c_common/c_common.c
> +    ensure(buffer != NULL, "malloc failed");
code change

2020-12-28 16:46 UTC, danwinkler commented
@zack-erisyon I'm in general a believer in using auto code formatters everywhere, so I took this as an opportunity to try and encode your style for clang-format. I didn't get it perfect, so let me know if there's anything in particular that bugs you about this formatting style.

I've also marked the places where actual code changes occur in c code to make it easier to review.

2020-12-28 16:56 UTC, zack-erisyon approved these changes

2020-12-28 17:00 UTC, merged