Wheels
erisyon/plaster pull request #236
Opened 2021-03-09 20:44 UTC by danwinkler

Keeping notes here:
https://github.com/erisyon/internal/blob/DHW110/wheels/internal/explore/plaster_wheel_test/README.md

2021-03-12 23:31 UTC, danwinkler commented
@zack-erisyon can I get rid of the vendored pyflann?

2021-03-16 17:35 UTC, zack-erisyon requested changes

2021-03-16 17:35 UTC, zack-erisyon commented on Dockerfile
> -FROM buildpack-deps:focal AS flann-build
Ahh, so nice to see this all go away. :-)

2021-03-16 17:35 UTC, zack-erisyon commented on Dockerfile
>  COPY ./plaster_root /erisyon/plaster/plaster_root
Do we still want to do this?

2021-03-16 17:35 UTC, zack-erisyon commented on Dockerfile
>  COPY ./plas /erisyon/plaster/plas
I got rid of plas and changed to p

2021-03-16 17:35 UTC, zack-erisyon commented on Dockerfile
>  COPY ./scripts/docker_entrypoint.py ./plaster/scripts/docker_entrypoint.py
Is this still used? When I look at docker_entrypoint.py it looks like a stub. For example, see the odd line: "__main++"

2021-03-16 17:35 UTC, zack-erisyon commented on Pipfile
> +pandas = "*"
Nice!

2021-03-16 17:35 UTC, zack-erisyon commented on build_wheels.sh
> +./scripts/build_manylinux.sh
Feels like this build_wheels.sh go into ./scripts?

2021-03-16 17:35 UTC, zack-erisyon commented on plaster/run/nn_v2/c/_nn_v2.h
> +// This file was code-generated by nn_v2.c.nn_v2.load_lib
I think that the code generator that wrote this line should also say "but this is intended to be version controlled" or some such thing that makes it clear why this is in version control / giviing a justificaiton for this so we don't forget

2021-03-16 17:35 UTC, zack-erisyon commented on plaster/run/nn_v2/c/build.py
> +import pathlib
I assume this is because setup context needs to not use plumbum. We should probably add a docstring or comment reminding our future selves that this (and other build.py) must only used core python modules

2021-03-16 17:35 UTC, zack-erisyon commented on plaster/run/nn_v2/zests/zest_nn_v2_worker.py
> +    from plaster.run.nn_v2.c.nn_v2 import _init as nn_v2_init
I just killed this off in master. Seemed to me that this line and the nn_v2_init() line below were wrong.

2021-03-16 17:35 UTC, zack-erisyon commented on plaster/run/sigproc_v2/c_gauss2_fitter/build.py
> +    # TODO: do we need to run cmake in the levmar folder and tell it to put it's output in the output dir?
What was the result of this comment?

2021-03-16 17:35 UTC, zack-erisyon commented on plaster/run/sigproc_v2/c_radiometry/_radiometry.h
> +// This file was code-generated by sigproc_v2.c_radiometry.c_radiometry.load_lib
Same note as above. More comment in the code generator about version control

2021-03-16 17:35 UTC, zack-erisyon commented on plaster/run/sigproc_v2/c_radiometry/build.py
>      # The CSA spline code is not working well yet and is not being used.
Let's cut this csa spline comment and the source files if they are still there. Ie I want to remove all references to CSA spline everywhere

2021-03-16 17:35 UTC, zack-erisyon commented on plaster/run/sim_v2/c/_sim_v2.h
> +                    typedef struct {
There should be a way to fix this indent ugliness in the code generator

2021-03-16 17:35 UTC, zack-erisyon commented on plaster/tools/zap/zap.py
>          # so I pinned Pandas back to 1.0.5
Seems like this comment can go away.
I remember that the reason I call .apply had to do with getting args or return in to the right form somehow. I guess we'll find out when something goes wrong. :-O

2021-03-16 17:35 UTC, zack-erisyon commented on scripts/build_wheels_inside_manylinux.sh
> +    wheel="$1"
Some docs here that explains what you learned about repair wheel would be good (generally for thie whole file)

2021-03-16 17:35 UTC, zack-erisyon commented on scripts/build_wheels_inside_manylinux.sh
> +# yum install -y atlas-devel
Kill?

2021-03-16 22:00 UTC, danwinkler commented on build_wheels.sh
> +./scripts/build_manylinux.sh
done

2021-03-16 22:06 UTC, danwinkler commented on plaster/run/sigproc_v2/c_gauss2_fitter/build.py
> +    # TODO: do we need to run cmake in the levmar folder and tell it to put it's output in the output dir?
Answer: no, because we've version controlled the result of cmake. We could do that, it might be more correct, but leaving as is, as that was the behavior before and I'm trying to limit scope as much as possible as this PR is getting large. Updated the comment

2021-03-16 22:10 UTC, danwinkler commented on scripts/build_wheels_inside_manylinux.sh
> +# yum install -y atlas-devel
done

2021-03-16 22:17 UTC, danwinkler commented on Dockerfile
>  COPY ./plaster_root /erisyon/plaster/plaster_root
Out of scope for this PR

2021-03-16 22:26 UTC, zack-erisyon approved these changes
Woot

2021-03-16 22:26 UTC, merged