Tfb111/classify with radmat filtering
erisyon/plaster pull request #242
Opened 2021-03-15 20:41 UTC by tblom

2021-03-15 21:49 UTC, zack-erisyon requested changes

2021-03-15 21:49 UTC, zack-erisyon commented on plaster/gen/classify_v2_generator.py
> +        **RadFilterParams.defaults,
I don't think this is correct. If we don't push the defaults here they will get assigned a plaster run time

2021-03-15 21:49 UTC, zack-erisyon commented on plaster/gen/task_templates.py
> +def rad_filter(**kwargs):
This doesn't seem to match the above. You reference input_task_name. I think the pattern in the task_templates is to enumerate the kwargs instead of relying on **kwarging.

2021-03-15 21:49 UTC, zack-erisyon commented on plaster/run/nn_v2/c/nn_v2.py
> +        ("radmat_filter_mask", Tab, np.uint32 ),
You reference it here as a uint32 but in the C code above as a uint8

2021-03-16 05:54 UTC, tblom commented on plaster/gen/classify_v2_generator.py
> +        **RadFilterParams.defaults,
Ok, let's review that pattern.  I think I've tended to add these at the generator level so that there is visibility into what params a job/run is using within the plaster_run.yaml/run_manifest.yaml.  Otherwise how does a user see these params?  If I remove the defaults here, I also need to remove the schema for RadFilterParams (or add noneable to all those params?)

2021-03-16 05:56 UTC, tblom commented on plaster/gen/task_templates.py
> +def rad_filter(**kwargs):
fixed, input_task_name was from an earlier iteration when I was allowing sim_v2 to also get passed through a rad_filter task.  re: **kwarging, I need more clarity about default params as noted above.  If you don't supply defaults at the generator level, there are no params to write here.

2021-03-16 05:57 UTC, tblom commented on plaster/run/nn_v2/c/nn_v2.py
> +        ("radmat_filter_mask", Tab, np.uint32 ),
fixed, yeah I was switching between ints and bools and they got out of sync!

2021-03-16 17:19 UTC, merged