ZBS320/profile plaster
erisyon/plaster pull request #284
Opened 2021-05-03 20:04 UTC by zack-erisyon

- wip
- wip
- wip
- wip
- wip
- wip
- wip
- wip
- wip
- wip
- wip
- wip
- wip
- wip

2021-05-03 20:58 UTC, danwinkler requested changes
Not a fan of having profile logs end up under `plaster_profile`, and having to add new, identical configuration everywhere. Seems better to just have it under plaster, leave all of the logging.yamls how they are, and if we want to tweak the profile logs specifically we can still do that. 

Otherwise lgtm

2021-05-03 20:58 UTC, danwinkler commented on plaster/tools/zlog/zlog.py
> +        log = logging.getLogger("plaster_profile")
Why is this logger not in the plaster namespace (`plaster.zlog.profile`)? Seems like the default behavior we'd want it for it to log like plaster unless we specifically override it (as shown by the added config lines you've added to all of the logging.yaml files).

2021-05-03 20:58 UTC, danwinkler commented on plaster/tools/zlog/zlog.py
> +    log.info(
Might make sense to have the level be configurable at some point but this is fine for now

2021-05-04 02:34 UTC, zack-erisyon commented on plaster/tools/zlog/zlog.py
> +        log = logging.getLogger("plaster_profile")
done

2021-05-04 02:34 UTC, merged