an attempt at surfacing per_channel peak locations
erisyon/plaster pull request #354
Opened 2021-09-16 20:55 UTC by danwinkler

2021-09-24 13:55 UTC, zack-erisyon requested changes

2021-09-24 13:55 UTC, zack-erisyon commented on plaster/run/sigproc_v2/peak_find.py
> +            circle = draw.disk(loc, radius)
This is likely regenerating the disc inside the loop.
I have some tools in imops for this op.

circle_im = imops.generate_circle_mask(rad=2)
imops.accum_inplace(im, circle_im, loc=YX(loc), center=True)

2021-09-24 13:55 UTC, zack-erisyon commented on plaster/run/sigproc_v2/peak_find.py
> +    table = np.zeros((4 + 2 * n_channels, locs.shape[0]))
+4 ??
I'm not sure why this table is needed at all vs using the locs as is

2021-09-24 13:55 UTC, zack-erisyon commented on plaster/run/sigproc_v2/peak_find.py
> +def _dedupe_peaks(locs_per_channel: List[np.ndarray]) -> np.ndarray:
Seems like this func now un-used.  Maybe comment it out / move to archive?

2021-09-24 13:55 UTC, zack-erisyon commented on plaster/run/sigproc_v2/zests/zest_peak_find.py
> +    def it_dedupes_peaks():
Tests associated with now deprecated func? See above comment

2021-09-24 13:55 UTC, zack-erisyon commented on plaster/run/sigproc_v2/zests/zest_peak_find.py
> +            print(n_found_ch0, n_true_ch0, " ")
Remove debugging. And, BTW, better to use spy or tell in this case

2021-09-28 17:41 UTC, danwinkler commented on plaster/run/sigproc_v2/c_peak_find/peak_find.c
> +                        // TODO: memory leak here! Ask Zack if there's a way to allocate a fixed size array in a fixupstruct
@zack-erisyon

2021-09-28 17:42 UTC, danwinkler commented on plaster/run/sigproc_v2/peak_find.py
> +            # TODO: @ZBS: is there a way to use your imops.generate_circle_mask, but set a different value for each location?
@zack-erisyon

2021-09-28 17:42 UTC, danwinkler commented on plaster/run/sigproc_v2/peak_find.py
> +    # TODO: @ZBS Ideas on how to numpyify this?
@zack-erisyon

2021-09-28 17:48 UTC, zack-erisyon commented on plaster/run/sigproc_v2/c_peak_find/peak_find.c
> +                        // TODO: memory leak here! Ask Zack if there's a way to allocate a fixed size array in a fixupstruct
It doesn't seem like we need this malloc.  Can't the outer subloc simply be allocated large enough for the worst case?

2021-09-28 17:49 UTC, zack-erisyon commented on plaster/run/sigproc_v2/peak_find.py
> +            # TODO: @ZBS: is there a way to use your imops.generate_circle_mask, but set a different value for each location?
You want a different value for each loc because you want sub-pixel? I was thinking you just use a coarse pixel-scale marker that you genreate with generate_circle_mask() outside the loop and then splat it on integer-pixel boundaries (ie round the sub-pix to pix)

2021-09-28 17:54 UTC, zack-erisyon commented on plaster/run/sigproc_v2/peak_find.py
> +    # TODO: @ZBS Ideas on how to numpyify this?
Something like this... I'm not positive what the shapes of everything are but the
idea is that you have loc_id have a shape of (n_locs, n_channels) and you have locs_per_channel look similar.
Then you use np.where()

# Make loc_id be shape (n_locs, n_channels)
locs = np.where(loc_id > 0, locs_per_channel[loc_id-1], np.nan )

2021-09-28 18:01 UTC, danwinkler commented on plaster/run/sigproc_v2/c_peak_find/peak_find.c
> +                        // TODO: memory leak here! Ask Zack if there's a way to allocate a fixed size array in a fixupstruct
I'd like the struct to be 
```c
typedef struct {
    Index loc_ids[N_MAX_CHANNELS];
    Size ambiguous;
} SubLoc;
```

but the structs are code generated by the FixupStructure python class. Is there a way to code generate fixed size arrays as struct members?

2021-09-28 18:02 UTC, danwinkler commented on plaster/run/sigproc_v2/peak_find.py
> +            # TODO: @ZBS: is there a way to use your imops.generate_circle_mask, but set a different value for each location?
I need a different value because I need to encode the loc id in the image

2021-09-28 19:56 UTC, zack-erisyon approved these changes

2021-09-28 19:58 UTC, merged